"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tipo = void 0;
var Tipo;
(function (Tipo) {
    Tipo[Tipo["CADENA"] = 0] = "CADENA";
    Tipo[Tipo["ENTERO"] = 1] = "ENTERO";
    Tipo[Tipo["DECIMAL"] = 2] = "DECIMAL";
    Tipo[Tipo["CHAR"] = 3] = "CHAR";
    Tipo[Tipo["BOOL"] = 4] = "BOOL";
    Tipo[Tipo["POSITION"] = 5] = "POSITION";
    Tipo[Tipo["LAST"] = 6] = "LAST";
    Tipo[Tipo["IDENTIFICADOR"] = 7] = "IDENTIFICADOR";
    Tipo[Tipo["NULL"] = 8] = "NULL";
    Tipo[Tipo["VOID"] = 9] = "VOID";
    Tipo[Tipo["INT_FUNCTION"] = 10] = "INT_FUNCTION";
    Tipo[Tipo["DOUBLE_FUNCTION"] = 11] = "DOUBLE_FUNCTION";
    Tipo[Tipo["STRING_FUNCTION"] = 12] = "STRING_FUNCTION";
    Tipo[Tipo["CHAR_FUNCTION"] = 13] = "CHAR_FUNCTION";
    Tipo[Tipo["BOOLEAN_FUNCTION"] = 14] = "BOOLEAN_FUNCTION";
    Tipo[Tipo["IF"] = 15] = "IF";
    Tipo[Tipo["WHILE"] = 16] = "WHILE";
    Tipo[Tipo["DO_WHILE"] = 17] = "DO_WHILE";
    Tipo[Tipo["SWITCH"] = 18] = "SWITCH";
    Tipo[Tipo["FOR"] = 19] = "FOR";
    Tipo[Tipo["ATRIBUTO"] = 20] = "ATRIBUTO";
    Tipo[Tipo["ARRAY"] = 21] = "ARRAY";
    Tipo[Tipo["STRUCT"] = 22] = "STRUCT";
    Tipo[Tipo["PRINT"] = 23] = "PRINT";
    Tipo[Tipo["BREAK"] = 24] = "BREAK";
    Tipo[Tipo["CONTINUE"] = 25] = "CONTINUE";
    Tipo[Tipo["RETURN"] = 26] = "RETURN";
})(Tipo = exports.Tipo || (exports.Tipo = {}));
